---
- name: Downloads files
  hosts: localhost
  become: true
  become_method: sudo
  vars_prompt:
    - name: URL
      prompt: "Enter URL: "
      private: false
  tasks:
    - name: Doanload 1 package
      get_url:
        url: "{{URL}}"
        dest: /tmp/