---
- name: Downloads files
  vars_prompt:
    - name: URL
      prompt: "Enter URL"
      private: false
    - name: Destination
      prompt: "Enter path"
      private: false
    - name: HOST
      prompt: "Enter host"
      private: false

  hosts: "{{HOST}}"
  become: true
  become_method: sudo
  
  tasks:
    - name: Doanload 1 package
      get_url:
        url: "{{URL}}"
        dest: "{{Destination}}"