---
- name: Install filebeat
  hosts: all
  become: yes
  become_user: root
  tasks:
    - block:

      - name: Install filebeat on CentOS 6
        package:
          name: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.5.2-x86_64.rpm"
          state: latest
        notify: FILEBEAT_6
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
      


    - block:

      - name: Download filebeat on CentOS 7
        package:
          name: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.5.2-x86_64.rpm"
          state: latest
        notify: FILEBEAT_7
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
      

  handlers:
    - name: FILEBEAT_6
      service:
        name: filebeat
        state: restarted

    - name: FILEBEAT_7
      service:
        name: filebeat
        state: restarted        