---
- name: Install nagios agent 
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Create repo on CentOS 6
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
      package:
        name: "http://repo.nagios.com/nagios/6/nagios-repo-6-3.el6.noarch.rpm"
        state: latest

    - name: Install ncpa on CentOS 6
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
      package:
        name: ncpa
        state: present
      notify: NCPA_CENTOS_6

    - name: Create repo
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
      package:
        name: "https://repo.nagios.com/nagios/7/nagios-repo-7-4.el7.noarch.rpm"
        state: latest

    - name: Install ncpa on CentOS 7
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
      package:
        name: ncpa
        state: present
      notify: NCPA_CENTOS_7

  

  handlers:
    - name: NCPA_CENTOS_6
      service:
        name: ncpa_listener
        state: restarted

    - name: NCPA_CENTOS_6
      lineinfile:
        path: /usr/local/ncpa/etc/ncpa.cfg
        regexp: "community_string = mytoken"
        line: "community_string = redhat"

    - name: NCPA_CENTOS_7
      service:
        name: ncpa_listener.service
        state: restarted
    - name: NCPA_CENTOS_7
      lineinfile:
        path: /usr/local/ncpa/etc/ncpa.cfg
        regexp: "community_string = mytoken"
        line: "community_string = redhat"

