---
- name: Restart all types of OS
  vars_prompt: 
    name: OS_TYPE
    private: false
  hosts: localhost
  tasks:
    - name: Restart
      when: ansible_distribution == "{{OS_TYPE}}"
      reboot:
        
