---
- name: Install wordpress
  hosts: web
  become: true
  become_method: sudo
  gather_facts: false

  connection: ssh
  tasks:
    - name: Install necessary packages
      package:
        name: "{{item}}"
        state: latest
      with_items:
        - wget
        - unzip
        - php-gd
        - httpd
        - mysql
        - mariadb-server
        - php
        - php-mysql
        - php-fpm
      ignore_errors: true

    - name: Doanload wordpress package
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: /tmp/

    - name: Unzip wordpress file
      unarchive:
        src: "/tmp/latest.tar.gz"
        dest: /var/www/html/wordpress
      become: true
      become_method: sudo

    - name: Move files to html folder
      shell: " mv /var/www/html/wordpress/* /var/www/html"
      become: true
      become_method: sudo
      ignore_errors: true

    - name: Start httpd
      systemd: 
        name: httpd
        state: started
        enabled: true 
      become: true
      become_method: sudo
